# 문제 6

(kaggle 형 문제) **prob4**를 바탕으로 아래 데이터셋을 만든다.

. **prob6_train**: DateHour 변수 기준으로 2021년 8월 14일 전(8월 14일 미포함) 데이터 (행의 수: 5256개)

. **prob6_test**: DateHour 변수 기준으로 2021년 8월 14일 이후(8월 14일 포함) 데이터 (행의 수: 744 개)

일 때, **prob6_train**으로 target을 예측하는 모델을 만들어, 

**prob6_test**의 target에 대한 MAE를 최소화하는 모델을 만든다. 

$MAE(Y, \hat{Y})=\frac{1}{n}\sum^n_{i=1}|y_i - \hat{y_i}|$ 

**prob6_test**의 예측 결과를 아래와 같은 형식으로 출력한다. 파일명은 answer6.csv 이다.

|DateHour|TotalHour|
|--------|---------|
|2021-08-14 00:00:00|102.607580|
|2021-08-14 01:00:00|94.078890|
....

※ 실제 상황에 가까운 연습을 위해 **prob6_test**의 target 값은 모른다는 상황을 가정하고 문제를 푼다.

# Kaggle형 풀이 단계

Step 0: Kaggle용 데이터셋을 만든다.

Step 1: 검증 방법을 정하고, 검증 루틴을 만듭니다. metric: MAE

Step 2: Baseline 모델을 만듭니다

Step 3: 모델 선택 루틴을 만듭니다.

|DateHour|	TotalHour|
|----|----|
|2021-08-14 00:00:00|	102.607580|
|2021-08-14 01:00:00|	94.078890|
....	

Step 4: 모델 개선 작업을 합니다.

## 데이터 전처리

In [16]:
# 실행 환경 확인

import pandas as pd
import numpy as np
import sklearn
import scipy
import statsmodels
#import mlxtend
import sys
#import xgboost as xgb

print(sys.version)
for i in [pd, np, sklearn, scipy, statsmodels]:
    print(i.__name__, i.__version__)

3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
pandas 0.25.1
numpy 1.18.5
sklearn 0.21.3
scipy 1.5.2
statsmodels 0.11.1

In [17]:
df_elec = pd.read_csv('elec.csv', parse_dates=['Date', 'DateHour'])
df_info = pd.read_csv('info.csv')
df_info['Date'] = pd.to_datetime(df_info['Date'])

In [18]:
df_elec1 = df_elec.pivot(
    index='DateHour', 
    columns='Minute', 
    values='Value').reset_index() # index에 위치한 DateHour를 컬럼에 위치시킵니다
df_elec1

Minute            DateHour  15분  30분  45분  60분
0      2021-01-01 00:00:00   62   61   61   61
1      2021-01-01 01:00:00   96   93  116  113
2      2021-01-01 02:00:00  106   96  106  107
3      2021-01-01 03:00:00   92  110  110  109
4      2021-01-01 04:00:00  108  105  106  108
...                    ...  ...  ...  ...  ...
6163   2021-09-14 19:00:00  152  151  171  139
6164   2021-09-14 20:00:00  124  130  128  130
6165   2021-09-14 21:00:00  134  130  125  124
6166   2021-09-14 22:00:00  100  109  120  114
6167   2021-09-14 23:00:00  117  119  112   91

[6168 rows x 5 columns]

In [19]:
holi = pd.to_datetime(["2021-01-01", "2021-02-11", "2021-02-12", "2021-03-01", "2021-05-05", "2021-05-19", "2021-08-16"]).date

# pd.Series.dt accessor를 통해 파생 변수들을 만듭니다.
df_elec1 = df_elec1.assign(
    DayName = df_elec1['DateHour'].dt.weekday, 
    Hour = df_elec1['DateHour'].dt.hour,
    AM = (df_elec1['DateHour'].dt.hour >= 12).astype('int'),
    Weekend_yn = df_elec1['DateHour'].dt.weekday.isin([5, 6]).astype('int'),
    Holiday_yn = df_elec1['DateHour'].dt.date.isin(holi).astype('int'), # df_elec1['DateHour'].dt.date는 pd.Series 입니다.
    Avg = df_elec1[['15분', '30분', '45분', '60분']].mean(axis=1),
    TotalHour = df_elec1[['15분', '30분', '45분', '60분']].sum(axis=1),
)

In [20]:
df_info1 = df_info.fillna(0)

In [21]:
df_basetable1 = df_elec1.merge(
    df_info1, 
    left_on='DateHour', 
    right_on='Date', how='inner'
).drop(columns='Date') # DateHour가 컬럼에 있으므로 DateHour, Date 모두 존재하여, Date는 삭제했습니다.
display(df_basetable1.head())
df_basetable1.shape

,DateHour,15분,30분,45분,60분,DayName,Hour,AM,Weekend_yn,Holiday_yn,Avg,TotalHour,생산량,기온,풍속,습도,강수량,전기요금(계절),공장인원,인건비
0,2021-01-01 00:00:00,62,61,61,61,4,0,0,0,1,61.25,245,0,-3.2,2.4,71,0.0,109.8,0.0,1.5
1,2021-01-01 01:00:00,96,93,116,113,4,1,0,0,1,104.50,418,0,-4.5,1.5,77,0.0,109.8,0.0,1.5
2,2021-01-01 02:00:00,106,96,106,107,4,2,0,0,1,103.75,415,0,-3.9,2.6,58,0.0,109.8,0.0,1.5
3,2021-01-01 03:00:00,92,110,110,109,4,3,0,0,1,105.25,421,0,-4.1,2.6,56,0.0,109.8,0.0,1.5
4,2021-01-01 04:00:00,108,105,106,108,4,4,0,0,1,106.75,427,0,-4.6,2.6,60,0.0,109.8,0.0,1.5

(6168, 20)

In [22]:
# shift를 이용합니다.
df_prob3 = df_basetable1.sort_values('DateHour').reset_index(drop=True)
df_prob3['target'] = df_prob3['TotalHour'].shift(-24)
df_prob4 = pd.concat(
    [df_prob3] + [
        df_prob3['TotalHour'].shift(24 * i).rename('lag_{}'.format(i)) for i in range(1, 7)
    ], axis=1
).dropna()
df_prob4.head()

,DateHour,15분,30분,45분,60분,DayName,Hour,AM,Weekend_yn,Holiday_yn,...,전기요금(계절),공장인원,인건비,target,lag_1,lag_2,lag_3,lag_4,lag_5,lag_6
144,2021-01-07 00:00:00,22,22,22,25,3,0,0,0,0,...,109.8,0.000000,1.5,252.0,96.0,96.0,271.0,88.0,253.0,245.0
145,2021-01-07 01:00:00,26,22,22,22,3,1,0,0,0,...,109.8,0.369565,1.5,396.0,85.0,85.0,432.0,99.0,418.0,418.0
146,2021-01-07 02:00:00,22,21,21,22,3,2,0,0,0,...,109.8,0.000000,1.5,411.0,85.0,85.0,439.0,88.0,415.0,415.0
147,2021-01-07 03:00:00,22,22,22,23,3,3,0,0,0,...,109.8,0.629213,1.5,398.0,90.0,90.0,426.0,88.0,421.0,421.0
148,2021-01-07 04:00:00,22,26,26,23,3,4,0,0,0,...,109.8,2.865979,1.5,420.0,93.0,93.0,435.0,95.0,427.0,427.0

In [23]:
# shift를 사용하지 않고 target를 구하는 방법입니다. (값을 구하기만 하고, 따로 prob4로 만들지는 않았습니다.)
df_basetable1.join(
    df_basetable1[['DateHour','TotalHour']].assign(
        DateHour=lambda x: x['DateHour'] - pd.Timedelta(days=1)
    ).set_index('DateHour').rename(columns={'TotalHour': 'target'}),
    on='DateHour', how='inner'
)

,DateHour,15분,30분,45분,60분,DayName,Hour,AM,Weekend_yn,Holiday_yn,...,TotalHour,생산량,기온,풍속,습도,강수량,전기요금(계절),공장인원,인건비,target
0,2021-01-01 00:00:00,62,61,61,61,4,0,0,0,1,...,245,0,-3.2,2.4,71,0.0,109.8,0.000000,1.5,253
1,2021-01-01 01:00:00,96,93,116,113,4,1,0,0,1,...,418,0,-4.5,1.5,77,0.0,109.8,0.000000,1.5,418
2,2021-01-01 02:00:00,106,96,106,107,4,2,0,0,1,...,415,0,-3.9,2.6,58,0.0,109.8,0.000000,1.5,415
3,2021-01-01 03:00:00,92,110,110,109,4,3,0,0,1,...,421,0,-4.1,2.6,56,0.0,109.8,0.000000,1.5,421
4,2021-01-01 04:00:00,108,105,106,108,4,4,0,0,1,...,427,0,-4.6,2.6,60,0.0,109.8,0.000000,1.5,427
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6139,2021-09-13 19:00:00,162,160,148,122,0,19,1,0,0,...,592,2820,22.3,2.1,78,0.0,167.2,4.763514,1.5,613
6140,2021-09-13 20:00:00,113,122,122,126,0,20,1,0,0,...,483,14,22.2,1.3,78,0.0,167.2,0.028986,1.5,512
6141,2021-09-13 21:00:00,122,131,122,115,0,21,1,0,0,...,490,72,21.9,1.9,77,0.0,167.2,0.146939,1.5,513
6142,2021-09-13 22:00:00,97,108,122,113,0,22,1,0,0,...,440,11,21.7,1.4,77,0.0,167.2,0.025000,1.5,443
6143,2021-09-13 23:00:00,111,123,110,87,0,23,1,0,0,...,431,345,21.4,1.4,80,0.0,167.2,0.800464,1.5,439

In [24]:
# 문제에서 제시한 데이터셋을 만듭니다.
df_prob6_train = df_prob4.loc[df_prob4['DateHour'] < pd.to_datetime('2021-08-14 00:00:00')]
df_prob6_test = df_prob4.loc[df_prob4['DateHour'] >= pd.to_datetime('2021-08-14 00:00:00')]
# 정답 target은 떼어냅니다.
s_kaggle_ans =  df_prob6_test.pop('target') # Kaggle의 정답으로 간주하겠습니다, 실제 시험에서는 공개 되지 않습니다.

## Step 1: 검증 방법을 정하고, 검증 루틴을 만듭니다.

- 평가 방법: 실제 ML 모델이 투입이 되었을 경우의 상황을 고려하여 설계합니다
> 이 Task의 구성: 지금까지 누적된 데이터를 가지고 미래의 TotalHour를 예측하는 모델으 만듭니다. 
>
>  모델의 학습주기: 1개월 
  
  
- 검증 방법 정하기
> 분리 방법: Random, 계층적(Stratfied), 그룹(동일한 그룹 분리가 되지 않게), 시점 기준 분리, ...
>
> 진행 방법
>   * Hold-out (train / valid) => 결과의 편차가 크지 않은 경우
>
>   * cross-validation => n개의 셋으로 나누어, 하나씩 학습제외하고 검증셋 지정하여 n번의 검증을 통해 평균으로 성능 측정
>
>   * Monte Carlo => Hold-out 또는 cv 셋의 구성 달리하며 n번 수행 하는 것 


- ML에 있어 핵심 입니다.

In [25]:
df_prob6_test['DateHour'].agg(['min', 'max'])

min   2021-08-14 00:00:00
max   2021-09-13 23:00:00
Name: DateHour, dtype: datetime64[ns]

In [34]:
X_all = df_prob6_test.columns.tolist()
np.array(X_all)

array(['DateHour', '15분', '30분', '45분', '60분', 'DayName', 'Hour', 'AM',
       'Weekend_yn', 'Holiday_yn', 'Avg', 'TotalHour', '생산량', '기온', '풍속',
       '습도', '강수량', '전기요금(계절)', '공장인원', '인건비', 'lag_1', 'lag_2', 'lag_3',
       'lag_4', 'lag_5', 'lag_6'], dtype='<U10')

In [28]:
df_train = df_prob6_train.loc[df_prob6_train['DateHour'] < pd.to_datetime('2021-07-14 00:00:00')]
df_valid = df_prob6_train.loc[df_prob6_train['DateHour'] >= pd.to_datetime('2021-07-14 00:00:00')]

In [29]:
df_valid['DateHour'].agg(['min', 'max'])

min   2021-07-14 00:00:00
max   2021-08-13 23:00:00
Name: DateHour, dtype: datetime64[ns]

## Step2: Baseline Model 모델을 만듭니다.

**Idea**

- 모델
> SVR - kernel - 'rbf', C = 10, gamma = 0.1
  
- 전처리 
> 표준화: 'TotalHour', 'lag_1' ~ 'lag_6' 
>
> 가변수화: 'DayName'
>
>통과: 'AM'

In [60]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import make_pipeline

from sklearn.svm import SVR

ct = ColumnTransformer([
    ('std', StandardScaler(), ['TotalHour'] + ['lag_{}'.format(i) for i in range(1, 7)]),
    ('ohe', OneHotEncoder(categories='auto'), ['DayName']),
    ('pt', 'passthrough', ['AM'])
])

reg_svr = make_pipeline(
    ct, SVR(kernel = 'rbf', C = 10, gamma = 0.1)
)
reg_svr.fit(df_train[X_all], df_train['target'])

Pipeline(memory=None,
         steps=[('columntransformer',
                 ColumnTransformer(n_jobs=None, remainder='drop',
                                   sparse_threshold=0.3,
                                   transformer_weights=None,
                                   transformers=[('std',
                                                  StandardScaler(copy=True,
                                                                 with_mean=True,
                                                                 with_std=True),
                                                  ['TotalHour', 'lag_1',
                                                   'lag_2', 'lag_3', 'lag_4',
                                                   'lag_5', 'lag_6']),
                                                 ('ohe',
                                                  OneHotEncoder(categorical_features=None,
                                                                categories='auto',
                                                                drop=None,
                                                                dtype=<class 'numpy.float64'>,
                                                                handle_unknown='error',
                                                                n_values=None,
                                                                sparse=True),
                                                  ['DayName']),
                                                 ('pt', 'passthrough', ['AM'])],
                                   verbose=False)),
                ('svr',
                 SVR(C=10, cache_size=200, coef0=0.0, degree=3, epsilon=0.1,
                     gamma=0.1, kernel='rbf', max_iter=-1, shrinking=True,
                     tol=0.001, verbose=False))],
         verbose=False)

In [58]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(
    df_valid['target'], reg_svr.predict(df_valid[X_all])
)

145.34693972591637

In [59]:
# Kaggle 루틴의 원리의 이해에 도움을 드리기 위해
# 동일한 과정을 ColumnTransformer와 Pipeline없이 구성해봅니다. 
# 검증 과정에 해당하는 것이고, 
# 선택 과정은 이와 같은 과정으로 데이터를 바꿔서 수행 루틴을 구성해야 합니다.
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler, OneHotEncoder

std_scaler = StandardScaler()
ohe = OneHotEncoder(categories='auto', sparse = False)
X_std= ['TotalHour'] + ['lag_{}'.format(i) for i in range(1, 7)]
X_ohe = ['DayName']
X_pt = ['AM']
std_scaler.fit(df_train[X_std])
ohe.fit(df_train[X_ohe])

reg_svr_direct = SVR(kernel = 'rbf', C = 10, gamma = 0.1)
reg_svr_direct.fit(
    pd.concat([
        pd.DataFrame(std_scaler.transform(df_train[X_std]), index = df_train.index),
        pd.DataFrame(ohe.transform(df_train[X_ohe]), index =df_train.index),
        df_train[X_pt]
    ], axis=1), df_train['target']
)
prd = reg_svr_direct.predict(
    pd.concat([
        pd.DataFrame(std_scaler.transform(df_valid[X_std]), index = df_valid.index),
        pd.DataFrame(ohe.transform(df_valid[X_ohe]), index = df_valid.index),
        df_valid[X_pt]
    ], axis=1)
)

print("Without ColumnTransformer & Pipeline", mean_absolute_error(df_valid['target'], prd)) # 145.34693972591637

Without ColumnTransformer & Pipeline 145.34693972591637

## Step3: 모델 선택

**prob6_test**의 예측 결과를 아래와 같은 형식으로 출력한다. 파일명은 answer6.csv 이다.

|DateHour|TotalHour|
|--------|---------|
|2021-08-14 00:00:00|102.607580|
|2021-08-14 01:00:00|94.078890|

In [63]:
reg_svr.fit(df_prob6_train[X_all], df_prob6_train['target'])
prd = reg_svr.predict(df_prob6_test[X_all])
prd

array([ 80.88583003,  84.99642555,  90.73510936,  85.21184197,
        79.06669589,  80.84785986,  70.96165824,  51.42532078,
       125.41861586, 110.09505354, 103.53626616, 114.55107513,
        94.31011692, 104.95120092, 113.15932455,  93.74058225,
       106.4983882 ,  98.8500524 ,  88.31366552,  74.60278888,
        71.52830305,  83.31550006,  83.74107278,  79.91465722,
       117.00830223,  98.99707673,  83.73885314,  87.27788215,
        84.71961563, 100.16264481,  79.28361259, 280.67557272,
       675.78483488, 692.54417476, 685.28278835, 678.47007208,
       520.35423355, 676.01874191, 677.36093218, 672.1553248 ,
       686.62387569, 607.56351054, 452.77917557, 429.42464101,
       458.10203117, 461.79261398, 440.67331093, 380.76699066,
       255.90302787, 378.06880866, 384.52973608, 390.31102492,
       397.77935678, 317.24210188, 390.58944612, 510.88737554,
       659.71235076, 681.76698248, 659.63270342, 665.74417254,
       435.74549263, 654.95937218, 636.98219927, 620.5172515 ,
       620.35281108, 518.21686304, 597.97574998, 575.33585875,
       495.35968993, 486.72676509, 427.52268541, 399.41127544,
       282.97108936, 393.30552715, 429.28641614, 399.45428772,
       419.06808558, 346.8506385 , 428.83161049, 499.59665243,
       662.91356696, 669.03546784, 644.3928093 , 667.39391603,
       426.53226765, 638.00023304, 633.88740822, 599.15292038,
       604.62047647, 480.54171448, 584.26596654, 533.66498903,
       461.31146334, 452.74788671, 420.04422978, 394.69998476,
       281.50961403, 392.26517815, 417.50186891, 384.2068508 ,
       394.71220509, 338.73637572, 408.60442608, 510.0646182 ,
       660.95082832, 663.8605685 , 644.86309315, 666.939901  ,
       445.95491834, 643.43131011, 646.56971152, 625.69486184,
       618.67812439, 517.47913341, 604.71026172, 563.50348781,
       487.48338404, 473.05234232, 451.67468024, 420.94745947,
       290.6047356 , 403.49682622, 439.34384868, 426.15260116,
       418.29554963, 351.83300044, 429.29525441, 519.22608731,
       717.29939134, 704.35959114, 692.75469618, 712.85603896,
       419.26088769, 684.05331825, 691.45884632, 645.10768121,
       667.61132536, 555.96480311, 636.59135055, 562.94937274,
       459.45225289, 444.16399185, 422.37041322, 381.24237755,
       260.1615887 , 386.40535753, 424.92299094, 371.12206098,
       388.01196274, 329.33441733, 361.89696345, 230.52052848,
        92.20853304,  91.58886714,  87.24578819, 110.90215353,
        99.47305178, 101.20324181, 106.97007743, 102.62387887,
       112.43619358, 117.32012646, 116.11601973,  93.92639229,
        87.21128822,  89.32293651,  96.76544757,  94.48560618,
        89.46341572,  92.35882092,  92.00841395,  93.47082581,
        99.57904544, 103.69573989,  90.03476124,  46.01809592,
        93.16304223,  96.60885924,  73.62218703,  89.87137342,
        84.85964946,  89.55969555,  87.70858733,  81.26382738,
        85.75125228,  85.56782454,  73.74235443,  76.83561882,
        74.92380522,  82.77079406,  75.58764932,  79.26372332,
       126.77249211,  95.77458088,  94.01608716,  96.60595693,
       100.47413053, 112.24254181,  93.42765459, 223.83400219,
       691.04083912, 709.2344702 , 618.64293495, 632.82839049,
       384.47230345, 628.58558332, 609.65800884, 577.73737302,
       518.92941115, 433.44002187, 416.62378483, 407.5896126 ,
       421.45688768, 463.9484004 , 390.6884565 , 382.8157422 ,
       259.14477964, 369.32785983, 386.33459758, 358.10876066,
       362.56481233, 321.14658358, 373.13779555, 493.56560957,
       673.50179529, 677.07800942, 664.0891983 , 675.4381853 ,
       459.78275087, 658.34764387, 656.03221307, 647.5606748 ,
       642.54123713, 529.44055132, 627.18303938, 567.80439714,
       491.03260256, 484.40698695, 452.91133461, 413.63492586,
       258.98367409, 396.35478109, 428.28086696, 388.5258513 ,
       407.65107294, 340.55100437, 422.00271236, 499.72859649,
       696.89151821, 695.60091138, 679.94217304, 691.22265921,
       442.48562514, 664.66013894, 678.2649264 , 667.23407616,
       673.07090537, 560.24829113, 615.95284279, 575.95587665,
       474.64078481, 468.59639216, 440.91899388, 391.03201268,
       293.22392831, 415.57078517, 440.0831093 , 410.2625809 ,
       430.31606053, 356.67265057, 429.91811966, 535.13959128,
       686.97003565, 683.36906956, 675.01133635, 678.44693939,
       457.79956637, 658.64789701, 670.52728399, 661.52192894,
       661.48425177, 570.40994021, 625.89969906, 586.46136127,
       490.6880227 , 495.1791105 , 460.32737226, 421.76153654,
       301.83251633, 417.1221082 , 447.70772443, 408.15793412,
       430.48892322, 367.70942185, 435.5851435 , 521.74414881,
       668.33314403, 654.52385147, 638.1637003 , 696.4888563 ,
       432.24643961, 674.65603314, 667.21408806, 634.34166835,
       661.63456776, 539.21458722, 618.06508401, 516.1773773 ,
       445.62928489, 465.45911139, 413.20817404, 381.84280811,
       260.22393716, 383.12388083, 423.28068139, 376.3508055 ,
       420.26045485, 363.50694229, 396.19605086, 286.80637184,
       100.71278933,  93.48763815,  91.94262214,  97.50711968,
        84.24835741,  95.12083457,  93.7354164 ,  85.38121705,
        74.02059872,  88.21057621,  86.18913351,  60.66079871,
        76.27642164,  79.84650627,  86.73316489, 105.29772708,
        92.81625544,  92.39465642,  96.50255171,  92.72359935,
        84.71466211,  88.37731468,  84.85414221,  46.93337799,
        86.91727874,  98.52214374,  81.78384205,  96.16764078,
        75.29242578,  98.43360988,  97.27855308,  93.75003111,
        85.64781786,  85.30113211, 102.99533483,  95.1593714 ,
       104.00870006,  98.38200464, 100.09533943, 105.6169489 ,
       130.15629706, 116.07970734, 113.1234918 , 122.34725634,
       110.16298818, 120.18682373, 113.51044351, 235.05641612,
       638.85934062, 669.22018084, 654.58951933, 681.19525196,
       448.62510595, 677.99926877, 673.66707269, 677.87945676,
       649.65051768, 588.61914594, 657.44784554, 574.49764149,
       468.40430644, 477.92643718, 446.08729329, 393.48765783,
       264.82456327, 417.18247789, 447.49538672, 414.98429641,
       433.12914492, 339.02048227, 424.7322694 , 517.7599424 ,
       685.39565344, 681.90116091, 678.84042178, 687.99066499,
       468.60101123, 668.4977217 , 677.42986063, 665.95189153,
       685.89051538, 582.52387166, 635.29335986, 605.19994875,
       505.9431203 , 514.48223005, 463.73758991, 425.96884355,
       309.22011534, 432.65756293, 454.07966308, 412.34863116,
       448.18553845, 373.24903973, 437.29454923, 504.56626981,
       670.02446063, 671.70253017, 683.24093872, 672.07178089,
       438.06398824, 662.58797157, 672.9523171 , 634.87042321,
       649.81905675, 534.48385343, 628.82616545, 587.8539425 ,
       546.18516622, 518.55456466, 467.65594692, 436.87514422,
       305.57813167, 436.43919172, 458.42507446, 407.34785072,
       457.96241798, 373.9061911 , 455.6468308 , 504.03617116,
       669.05984939, 671.18087811, 680.05038035, 672.37661412,
       460.05334364, 666.03191528, 674.73146032, 650.23040982,
       657.18093779, 547.98958824, 634.31457015, 606.32406078,
       549.05995964, 534.57627698, 485.52073479, 462.00236062,
       324.89787468, 445.22312832, 465.77312671, 426.20040711,
       462.48075728, 379.91264827, 452.90938189, 507.77877414,
       684.58933989, 672.91703874, 659.76383313, 675.59724912,
       414.60529884, 662.81764636, 644.6567757 , 635.91052588,
       621.13797124, 558.39925064, 588.05418266, 532.19330966,
       451.19653994, 443.06673221, 392.99905937, 414.5559892 ,
       289.89216438, 426.27215537, 449.10422871, 414.84615504,
       423.51255727, 354.4276752 , 409.36278288, 300.27899491,
       143.90566624, 142.53510417, 142.69788823, 142.0322604 ,
       132.58171919, 130.82756386, 135.42838116, 120.49862112,
       140.39500147, 101.53158128,  50.18148147,  39.23099466,
        17.57449443,  26.62243236,  36.18617656,  42.86391061,
        51.08995957,  45.12074621,  38.65005735,  49.94496579,
        42.93233963,  47.71848841,  43.37087318,  17.49753957,
        63.07688512,  70.64779979,  65.91175584,  90.91267624,
        73.76607428,  84.92716893,  96.2930809 ,  77.82281627,
        83.30968594,  94.94567693,  88.87672043,  76.97873647,
        67.4420588 ,  73.05992205,  76.55477383,  71.70075355,
       119.34574774,  87.98848348,  85.76336126,  88.64951571,
        83.44784064,  96.87799225,  89.74944895, 201.67205756,
       658.36696622, 665.59097089, 664.27833545, 666.5738136 ,
       450.16298851, 657.30726664, 646.92006405, 645.05638053,
       661.13003239, 574.53511503, 669.55265439, 613.06625583,
       529.83904008, 536.54996723, 464.02792099, 432.46140481,
       261.61408055, 417.68530722, 426.28586311, 395.41401008,
       427.99375066, 348.66987754, 438.99037911, 498.85850599,
       674.89516415, 667.25491619, 682.21429637, 669.51155597,
       456.26287409, 659.62128859, 660.78103778, 642.8536087 ,
       646.36650703, 544.85150733, 635.10470094, 604.02207123,
       561.88565568, 529.68720429, 473.03929129, 449.81747483,
       281.66495724, 444.12826603, 456.18018887, 416.69275487,
       457.45902918, 368.00145705, 468.0056016 , 523.77710393,
       685.70931466, 676.43064015, 675.3665919 , 682.06734324,
       447.4738052 , 668.39196082, 667.62214721, 647.34139633,
       633.76749771, 540.9154756 , 622.1895808 , 598.07650454,
       518.75654822, 515.46208064, 452.11346368, 433.80179502,
       295.98218673, 445.24554703, 464.99692031, 442.6673629 ,
       451.97640732, 380.55634821, 467.14301344, 554.34303834,
       674.85122213, 670.57064071, 663.82826206, 667.94513422,
       397.5944981 , 654.19161906, 663.7413942 , 649.9675878 ,
       642.38691995, 559.76848904, 631.11946032, 612.54511976,
       510.63847911, 524.40475633, 458.38475882, 447.70397076,
       292.11324583, 435.29826133, 461.54306635, 448.11020139,
       445.71195421, 381.74894542, 464.67876684, 538.84595725,
       668.03530687, 671.93875195, 652.54029159, 702.82116264,
       436.22960034, 654.33500486, 674.56348009, 616.0432142 ,
       632.60454857, 572.68259224, 614.44948502, 572.13590116,
       459.82343923, 443.64079799, 410.20962792, 394.70105515,
       265.8092797 , 421.07225092, 422.73401433, 399.48693406,
       434.59303537, 351.5259824 , 448.66239059, 293.70261696,
       118.58978289, 121.06953449, 116.91680838, 115.19913907,
       168.58799764, 115.77766927, 119.32931429, 112.2760982 ,
       122.29457906, 118.38194396,  90.80733016,  77.86795788,
        75.32747443,  72.45065001,  83.50285946,  80.70467162,
        88.01229863,  79.25850662,  72.93079938,  77.01345363,
        79.07296636,  76.85858271,  70.76829411,  58.36817876,
        94.51132571,  89.94589369,  90.66463583,  97.95080544,
       176.4516118 ,  94.50362262,  90.61093613,  89.39824419,
        81.85573568,  79.39989921,  81.00793498,  76.03726498,
        86.89653523,  78.13711728,  82.21059954,  76.35843642,
       118.83450721,  95.29673276,  91.01636266,  90.44406953,
        88.76314167, 101.51994346,  94.42782028, 220.43556573,
       672.05136845, 643.09130557, 681.55869385, 686.40872246,
       445.30989476, 640.22239315, 636.65647098, 643.7357093 ,
       611.07727592, 548.50581497, 633.86081833, 568.08614878,
       501.38167275, 510.50026069, 433.75158576, 406.60352477,
       267.29595607, 412.87070328, 430.90708533, 418.50843389,
       415.435145  , 352.00489728, 438.03014098, 542.34641109,
       683.58192626, 682.08663706, 681.48007248, 687.45590274,
       471.70228913, 679.72208434, 676.79936061, 658.64102068,
       656.22682089, 569.25422042, 628.33238504, 620.46275891,
       530.68683503, 529.52877124, 459.64760561, 437.28692884])

In [67]:
pd.DataFrame({
    'DateHour': df_prob6_test['DateHour'],
    'TotalHour': prd
}).to_csv('answer6.csv', index = None)